// Demo snapshot — used when no team ID is entered.
// Intentionally suboptimal starting XI to make optimizer recommendations visible.
// Includes 1 injured player, 1 doubtful, to exercise StatusDot logic.

import type { BootstrapStatic, Fixture, PicksResponse, EntryResponse } from "@/types/fpl";

export const DEMO_TEAM_ID = 0;
export const DEMO_GW = 35;

// Minimal bootstrap: only the players needed for demo + their teams
export const demoBootstrap: Pick<BootstrapStatic, "elements" | "teams" | "element_types" | "game_settings"> & {
  events: { id: number; name: string; is_current: boolean; is_next: boolean; finished: boolean }[];
} = {
  events: [
    { id: 34, name: "Gameweek 34", is_current: false, is_next: false, finished: true },
    { id: 35, name: "Gameweek 35", is_current: true, is_next: false, finished: false },
    { id: 36, name: "Gameweek 36", is_current: false, is_next: true, finished: false },
  ],
  game_settings: {
    squad_squadsize: 15,
    squad_squadplay: 11,
    squad_team_limit: 3,
    squad_total_spend: 1000,
    transfers_cap: 20,
    transfers_sell_on_fee: 0.5,
    ui_currency_multiplier: 10,
  },
  element_types: [
    { id: 1, singular_name: "Goalkeeper", singular_name_short: "GKP", plural_name: "Goalkeepers", plural_name_short: "GKP", squad_select: 2, squad_min_play: 1, squad_max_play: 1, ui_shirt_specific: false, sub_positions_locked: [12], element_count: 80 },
    { id: 2, singular_name: "Defender", singular_name_short: "DEF", plural_name: "Defenders", plural_name_short: "DEF", squad_select: 5, squad_min_play: 3, squad_max_play: 5, ui_shirt_specific: false, sub_positions_locked: [], element_count: 240 },
    { id: 3, singular_name: "Midfielder", singular_name_short: "MID", plural_name: "Midfielders", plural_name_short: "MID", squad_select: 5, squad_min_play: 2, squad_max_play: 5, ui_shirt_specific: false, sub_positions_locked: [], element_count: 280 },
    { id: 4, singular_name: "Forward", singular_name_short: "FWD", plural_name: "Forwards", plural_name_short: "FWD", squad_select: 3, squad_min_play: 1, squad_max_play: 3, ui_shirt_specific: false, sub_positions_locked: [], element_count: 120 },
  ],
  teams: [
    { id: 1, code: 3, name: "Arsenal", short_name: "ARS", strength: 5, strength_overall_home: 1310, strength_overall_away: 1280, strength_attack_home: 1290, strength_attack_away: 1240, strength_defence_home: 1270, strength_defence_away: 1260, played: 34, win: 22, draw: 6, loss: 6, points: 72, position: 2 },
    { id: 2, code: 7, name: "Aston Villa", short_name: "AVL", strength: 4, strength_overall_home: 1190, strength_overall_away: 1160, strength_attack_home: 1180, strength_attack_away: 1150, strength_defence_home: 1160, strength_defence_away: 1140, played: 34, win: 16, draw: 7, loss: 11, points: 55, position: 7 },
    { id: 3, code: 36, name: "Brentford", short_name: "BRE", strength: 3, strength_overall_home: 1080, strength_overall_away: 1050, strength_attack_home: 1070, strength_attack_away: 1040, strength_defence_home: 1060, strength_defence_away: 1040, played: 34, win: 12, draw: 8, loss: 14, points: 44, position: 13 },
    { id: 4, code: 8, name: "Brighton", short_name: "BHA", strength: 4, strength_overall_home: 1150, strength_overall_away: 1120, strength_attack_home: 1140, strength_attack_away: 1110, strength_defence_home: 1130, strength_defence_away: 1110, played: 34, win: 14, draw: 9, loss: 11, points: 51, position: 9 },
    { id: 5, code: 90, name: "Chelsea", short_name: "CHE", strength: 4, strength_overall_home: 1200, strength_overall_away: 1180, strength_attack_home: 1210, strength_attack_away: 1190, strength_defence_home: 1180, strength_defence_away: 1160, played: 34, win: 16, draw: 7, loss: 11, points: 55, position: 6 },
    { id: 6, code: 31, name: "Crystal Palace", short_name: "CRY", strength: 3, strength_overall_home: 1040, strength_overall_away: 1010, strength_attack_home: 1030, strength_attack_away: 1000, strength_defence_home: 1020, strength_defence_away: 1010, played: 34, win: 10, draw: 8, loss: 16, points: 38, position: 16 },
    { id: 7, code: 11, name: "Everton", short_name: "EVE", strength: 2, strength_overall_home: 980, strength_overall_away: 950, strength_attack_home: 970, strength_attack_away: 940, strength_defence_home: 960, strength_defence_away: 950, played: 34, win: 9, draw: 8, loss: 17, points: 35, position: 18 },
    { id: 8, code: 54, name: "Fulham", short_name: "FUL", strength: 3, strength_overall_home: 1060, strength_overall_away: 1030, strength_attack_home: 1050, strength_attack_away: 1020, strength_defence_home: 1040, strength_defence_away: 1020, played: 34, win: 12, draw: 7, loss: 15, points: 43, position: 14 },
    { id: 9, code: 40, name: "Ipswich", short_name: "IPS", strength: 2, strength_overall_home: 960, strength_overall_away: 940, strength_attack_home: 950, strength_attack_away: 930, strength_defence_home: 940, strength_defence_away: 930, played: 34, win: 6, draw: 8, loss: 20, points: 26, position: 20 },
    { id: 10, code: 2, name: "Leicester", short_name: "LEI", strength: 2, strength_overall_home: 970, strength_overall_away: 950, strength_attack_home: 960, strength_attack_away: 940, strength_defence_home: 950, strength_defence_away: 940, played: 34, win: 7, draw: 6, loss: 21, points: 27, position: 19 },
    { id: 11, code: 14, name: "Liverpool", short_name: "LIV", strength: 5, strength_overall_home: 1350, strength_overall_away: 1310, strength_attack_home: 1340, strength_attack_away: 1290, strength_defence_home: 1300, strength_defence_away: 1280, played: 34, win: 27, draw: 4, loss: 3, points: 85, position: 1 },
    { id: 12, code: 43, name: "Man City", short_name: "MCI", strength: 5, strength_overall_home: 1300, strength_overall_away: 1280, strength_attack_home: 1310, strength_attack_away: 1290, strength_defence_home: 1290, strength_defence_away: 1270, played: 34, win: 16, draw: 9, loss: 9, points: 57, position: 5 },
    { id: 13, code: 1, name: "Man Utd", short_name: "MUN", strength: 3, strength_overall_home: 1090, strength_overall_away: 1060, strength_attack_home: 1080, strength_attack_away: 1050, strength_defence_home: 1070, strength_defence_away: 1050, played: 34, win: 11, draw: 6, loss: 17, points: 39, position: 15 },
    { id: 14, code: 4, name: "Newcastle", short_name: "NEW", strength: 4, strength_overall_home: 1200, strength_overall_away: 1170, strength_attack_home: 1190, strength_attack_away: 1160, strength_defence_home: 1180, strength_defence_away: 1160, played: 34, win: 17, draw: 7, loss: 10, points: 58, position: 4 },
    { id: 15, code: 45, name: "Nott'm Forest", short_name: "NFO", strength: 3, strength_overall_home: 1100, strength_overall_away: 1070, strength_attack_home: 1090, strength_attack_away: 1060, strength_defence_home: 1080, strength_defence_away: 1070, played: 34, win: 15, draw: 7, loss: 12, points: 52, position: 8 },
    { id: 16, code: 49, name: "Southampton", short_name: "SOU", strength: 2, strength_overall_home: 960, strength_overall_away: 940, strength_attack_home: 950, strength_attack_away: 930, strength_defence_home: 940, strength_defence_away: 930, played: 34, win: 5, draw: 7, loss: 22, points: 22, position: 20 },
    { id: 17, code: 6, name: "Spurs", short_name: "TOT", strength: 4, strength_overall_home: 1160, strength_overall_away: 1130, strength_attack_home: 1150, strength_attack_away: 1120, strength_defence_home: 1140, strength_defence_away: 1120, played: 34, win: 13, draw: 8, loss: 13, points: 47, position: 12 },
    { id: 18, code: 57, name: "West Ham", short_name: "WHU", strength: 3, strength_overall_home: 1070, strength_overall_away: 1040, strength_attack_home: 1060, strength_attack_away: 1030, strength_defence_home: 1050, strength_defence_away: 1030, played: 34, win: 10, draw: 8, loss: 16, points: 38, position: 17 },
    { id: 19, code: 39, name: "Wolves", short_name: "WOL", strength: 3, strength_overall_home: 1050, strength_overall_away: 1020, strength_attack_home: 1040, strength_attack_away: 1010, strength_defence_home: 1030, strength_defence_away: 1010, played: 34, win: 11, draw: 6, loss: 17, points: 39, position: 16 },
    { id: 20, code: 21, name: "Bournemouth", short_name: "BOU", strength: 3, strength_overall_home: 1100, strength_overall_away: 1070, strength_attack_home: 1090, strength_attack_away: 1060, strength_defence_home: 1080, strength_defence_away: 1060, played: 34, win: 14, draw: 6, loss: 14, points: 48, position: 11 },
  ],
  elements: [
    // GKPs (2)
    { id: 100, code: 100, web_name: "Flekken", first_name: "Mark", second_name: "Flekken", photo: "100.jpg", team: 3, team_code: 36, element_type: 1, status: "a", now_cost: 45, cost_change_event: 0, cost_change_start: 0, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "8.2", total_points: 118, event_points: 6, points_per_game: "3.5", form: "5.8", ep_this: "5.5", ep_next: "5.0", minutes: 2880, goals_scored: 0, assists: 0, clean_sheets: 9, goals_conceded: 34, yellow_cards: 0, red_cards: 0, saves: 78, bonus: 18, bps: 520, influence: "360.2", creativity: "12.4", threat: "0.0", ict_index: "37.2", ict_index_rank: 290, ict_index_rank_type: 4, expected_goals: "0.00", expected_assists: "0.00", expected_goal_involvements: "0.00", expected_goals_conceded: "38.5", expected_goals_per_90: 0, expected_assists_per_90: 0, expected_goal_involvements_per_90: 0, expected_goals_conceded_per_90: 1.2, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.26, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 120000, transfers_out: 90000, transfers_in_event: 8000, transfers_out_event: 5000, value_form: "1.29", value_season: "26.2", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 1, squad_number: null },
    { id: 101, code: 101, web_name: "Raya", first_name: "David", second_name: "Raya Martin", photo: "101.jpg", team: 1, team_code: 3, element_type: 1, status: "a", now_cost: 56, cost_change_event: 1, cost_change_start: 3, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "24.1", total_points: 152, event_points: 8, points_per_game: "4.5", form: "6.8", ep_this: "6.2", ep_next: "6.0", minutes: 2880, goals_scored: 0, assists: 1, clean_sheets: 14, goals_conceded: 26, yellow_cards: 1, red_cards: 0, saves: 72, bonus: 32, bps: 640, influence: "420.8", creativity: "18.2", threat: "0.0", ict_index: "44.0", ict_index_rank: 210, ict_index_rank_type: 3, expected_goals: "0.00", expected_assists: "0.00", expected_goal_involvements: "0.00", expected_goals_conceded: "28.5", expected_goals_per_90: 0, expected_assists_per_90: 0, expected_goal_involvements_per_90: 0, expected_goals_conceded_per_90: 0.89, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.41, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 320000, transfers_out: 120000, transfers_in_event: 42000, transfers_out_event: 8000, value_form: "1.21", value_season: "27.1", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 4, squad_number: null },

    // DEFs (5)
    { id: 200, code: 200, web_name: "Alexander-Arnold", first_name: "Trent", second_name: "Alexander-Arnold", photo: "200.jpg", team: 11, team_code: 14, element_type: 2, status: "a", now_cost: 78, cost_change_event: 1, cost_change_start: 5, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "41.2", total_points: 186, event_points: 9, points_per_game: "5.5", form: "8.2", ep_this: "7.8", ep_next: "7.5", minutes: 2790, goals_scored: 3, assists: 11, clean_sheets: 14, goals_conceded: 20, yellow_cards: 3, red_cards: 0, saves: 0, bonus: 42, bps: 820, influence: "680.4", creativity: "840.6", threat: "420.2", ict_index: "194.6", ict_index_rank: 4, ict_index_rank_type: 1, expected_goals: "2.8", expected_assists: "9.4", expected_goal_involvements: "12.2", expected_goals_conceded: "22.1", expected_goals_per_90: 0.09, expected_assists_per_90: 0.30, expected_goal_involvements_per_90: 0.39, expected_goals_conceded_per_90: 0.71, starts: 31, starts_per_90: 0.91, clean_sheets_per_90: 0.41, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 1200000, transfers_out: 200000, transfers_in_event: 180000, transfers_out_event: 12000, value_form: "1.05", value_season: "23.8", penalties_order: null, direct_freekicks_order: 1, corners_and_indirect_freekicks_order: 1, in_dreamteam: true, dreamteam_count: 12, squad_number: null },
    { id: 201, code: 201, web_name: "Pedro Porro", first_name: "Pedro", second_name: "Porro", photo: "201.jpg", team: 17, team_code: 6, element_type: 2, status: "a", now_cost: 56, cost_change_event: 0, cost_change_start: 1, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "18.4", total_points: 128, event_points: 6, points_per_game: "3.8", form: "5.2", ep_this: "5.0", ep_next: "4.8", minutes: 2880, goals_scored: 2, assists: 5, clean_sheets: 8, goals_conceded: 38, yellow_cards: 4, red_cards: 0, saves: 0, bonus: 22, bps: 580, influence: "460.2", creativity: "380.4", threat: "260.2", ict_index: "110.8", ict_index_rank: 45, ict_index_rank_type: 2, expected_goals: "1.4", expected_assists: "4.2", expected_goal_involvements: "5.6", expected_goals_conceded: "40.2", expected_goals_per_90: 0.04, expected_assists_per_90: 0.13, expected_goal_involvements_per_90: 0.17, expected_goals_conceded_per_90: 1.25, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.24, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 280000, transfers_out: 140000, transfers_in_event: 24000, transfers_out_event: 18000, value_form: "0.93", value_season: "22.9", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: 2, in_dreamteam: false, dreamteam_count: 2, squad_number: null },
    { id: 202, code: 202, web_name: "Saliba", first_name: "William", second_name: "Saliba", photo: "202.jpg", team: 1, team_code: 3, element_type: 2, status: "a", now_cost: 60, cost_change_event: 0, cost_change_start: 2, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "27.8", total_points: 148, event_points: 8, points_per_game: "4.4", form: "6.5", ep_this: "6.2", ep_next: "5.8", minutes: 2880, goals_scored: 1, assists: 3, clean_sheets: 14, goals_conceded: 26, yellow_cards: 2, red_cards: 0, saves: 0, bonus: 28, bps: 650, influence: "560.4", creativity: "140.2", threat: "80.4", ict_index: "78.0", ict_index_rank: 90, ict_index_rank_type: 2, expected_goals: "0.8", expected_assists: "1.8", expected_goal_involvements: "2.6", expected_goals_conceded: "28.5", expected_goals_per_90: 0.03, expected_assists_per_90: 0.06, expected_goal_involvements_per_90: 0.08, expected_goals_conceded_per_90: 0.89, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.41, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 480000, transfers_out: 90000, transfers_in_event: 55000, transfers_out_event: 6000, value_form: "1.08", value_season: "24.7", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 5, squad_number: null },
    { id: 203, code: 203, web_name: "Trippier", first_name: "Kieran", second_name: "Trippier", photo: "203.jpg", team: 14, team_code: 4, element_type: 2, status: "i", now_cost: 69, cost_change_event: -1, cost_change_start: -2, cost_change_event_fall: 1, cost_change_start_fall: 2, selected_by_percent: "9.8", total_points: 82, event_points: 0, points_per_game: "3.2", form: "1.8", ep_this: "1.0", ep_next: "2.0", minutes: 1620, goals_scored: 1, assists: 4, clean_sheets: 6, goals_conceded: 22, yellow_cards: 1, red_cards: 0, saves: 0, bonus: 12, bps: 380, influence: "280.4", creativity: "320.6", threat: "180.2", ict_index: "78.2", ict_index_rank: 88, ict_index_rank_type: 2, expected_goals: "0.9", expected_assists: "3.4", expected_goal_involvements: "4.3", expected_goals_conceded: "18.1", expected_goals_per_90: 0.05, expected_assists_per_90: 0.19, expected_goal_involvements_per_90: 0.24, expected_goals_conceded_per_90: 1.0, starts: 18, starts_per_90: 0.53, clean_sheets_per_90: 0.33, chance_of_playing_this_round: 0, chance_of_playing_next_round: 25, news: "Ankle injury - doubtful for rest of season", news_added: "2025-03-20T10:00:00Z", transfers_in: 80000, transfers_out: 420000, transfers_in_event: 2000, transfers_out_event: 68000, value_form: "0.26", value_season: "11.9", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: 1, in_dreamteam: false, dreamteam_count: 0, squad_number: null },
    { id: 204, code: 204, web_name: "Mykolenko", first_name: "Vitaliy", second_name: "Mykolenko", photo: "204.jpg", team: 7, team_code: 11, element_type: 2, status: "a", now_cost: 44, cost_change_event: 0, cost_change_start: 0, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "4.2", total_points: 88, event_points: 4, points_per_game: "2.7", form: "3.5", ep_this: "3.2", ep_next: "2.8", minutes: 2520, goals_scored: 0, assists: 2, clean_sheets: 6, goals_conceded: 46, yellow_cards: 5, red_cards: 0, saves: 0, bonus: 8, bps: 390, influence: "280.2", creativity: "180.4", threat: "120.2", ict_index: "58.0", ict_index_rank: 160, ict_index_rank_type: 3, expected_goals: "0.2", expected_assists: "1.4", expected_goal_involvements: "1.6", expected_goals_conceded: "48.2", expected_goals_per_90: 0.01, expected_assists_per_90: 0.05, expected_goal_involvements_per_90: 0.06, expected_goals_conceded_per_90: 1.64, starts: 28, starts_per_90: 0.82, clean_sheets_per_90: 0.21, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 40000, transfers_out: 60000, transfers_in_event: 3000, transfers_out_event: 8000, value_form: "0.80", value_season: "20.0", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 0, squad_number: null },

    // MIDs (5)
    { id: 300, code: 300, web_name: "Salah", first_name: "Mohamed", second_name: "Salah", photo: "300.jpg", team: 11, team_code: 14, element_type: 3, status: "a", now_cost: 132, cost_change_event: 1, cost_change_start: 8, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "76.8", total_points: 254, event_points: 14, points_per_game: "7.5", form: "11.2", ep_this: "10.5", ep_next: "10.8", minutes: 2790, goals_scored: 24, assists: 14, clean_sheets: 14, goals_conceded: 20, yellow_cards: 1, red_cards: 0, saves: 0, bonus: 58, bps: 1140, influence: "940.6", creativity: "820.4", threat: "1200.8", ict_index: "296.4", ict_index_rank: 1, ict_index_rank_type: 1, expected_goals: "21.4", expected_assists: "11.8", expected_goal_involvements: "33.2", expected_goals_conceded: "20.1", expected_goals_per_90: 0.69, expected_assists_per_90: 0.38, expected_goal_involvements_per_90: 1.07, expected_goals_conceded_per_90: 0.65, starts: 31, starts_per_90: 0.91, clean_sheets_per_90: 0.41, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 2400000, transfers_out: 180000, transfers_in_event: 380000, transfers_out_event: 8000, value_form: "0.85", value_season: "19.2", penalties_order: 1, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: true, dreamteam_count: 22, squad_number: null },
    { id: 301, code: 301, web_name: "Palmer", first_name: "Cole", second_name: "Palmer", photo: "301.jpg", team: 5, team_code: 90, element_type: 3, status: "a", now_cost: 108, cost_change_event: 1, cost_change_start: 6, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "48.9", total_points: 218, event_points: 12, points_per_game: "6.4", form: "9.4", ep_this: "9.0", ep_next: "8.8", minutes: 2880, goals_scored: 18, assists: 12, clean_sheets: 7, goals_conceded: 38, yellow_cards: 2, red_cards: 0, saves: 0, bonus: 48, bps: 980, influence: "760.4", creativity: "980.6", threat: "880.4", ict_index: "262.4", ict_index_rank: 2, ict_index_rank_type: 1, expected_goals: "15.8", expected_assists: "10.4", expected_goal_involvements: "26.2", expected_goals_conceded: "38.5", expected_goals_per_90: 0.49, expected_assists_per_90: 0.32, expected_goal_involvements_per_90: 0.81, expected_goals_conceded_per_90: 1.19, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.21, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 1800000, transfers_out: 140000, transfers_in_event: 220000, transfers_out_event: 12000, value_form: "0.87", value_season: "20.2", penalties_order: 1, direct_freekicks_order: 1, corners_and_indirect_freekicks_order: null, in_dreamteam: true, dreamteam_count: 18, squad_number: null },
    { id: 302, code: 302, web_name: "Mbeumo", first_name: "Bryan", second_name: "Mbeumo", photo: "302.jpg", team: 3, team_code: 36, element_type: 3, status: "a", now_cost: 76, cost_change_event: 1, cost_change_start: 4, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "32.4", total_points: 188, event_points: 9, points_per_game: "5.5", form: "7.8", ep_this: "7.2", ep_next: "6.8", minutes: 2880, goals_scored: 18, assists: 7, clean_sheets: 0, goals_conceded: 0, yellow_cards: 3, red_cards: 0, saves: 0, bonus: 34, bps: 840, influence: "680.4", creativity: "580.6", threat: "920.4", ict_index: "219.4", ict_index_rank: 6, ict_index_rank_type: 1, expected_goals: "14.8", expected_assists: "6.2", expected_goal_involvements: "21.0", expected_goals_conceded: "48.5", expected_goals_per_90: 0.46, expected_assists_per_90: 0.19, expected_goal_involvements_per_90: 0.65, expected_goals_conceded_per_90: 1.51, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.0, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 680000, transfers_out: 120000, transfers_in_event: 95000, transfers_out_event: 8000, value_form: "1.03", value_season: "24.7", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 8, squad_number: null },
    { id: 303, code: 303, web_name: "Andreas", first_name: "Andreas", second_name: "Pereira", photo: "303.jpg", team: 8, team_code: 54, element_type: 3, status: "d", now_cost: 54, cost_change_event: 0, cost_change_start: -1, cost_change_event_fall: 0, cost_change_start_fall: 1, selected_by_percent: "7.2", total_points: 98, event_points: 0, points_per_game: "3.1", form: "2.8", ep_this: "2.5", ep_next: "3.0", minutes: 2340, goals_scored: 4, assists: 6, clean_sheets: 0, goals_conceded: 0, yellow_cards: 4, red_cards: 0, saves: 0, bonus: 18, bps: 520, influence: "380.4", creativity: "440.6", threat: "280.4", ict_index: "110.8", ict_index_rank: 44, ict_index_rank_type: 2, expected_goals: "3.4", expected_assists: "5.2", expected_goal_involvements: "8.6", expected_goals_conceded: "40.2", expected_goals_per_90: 0.13, expected_assists_per_90: 0.20, expected_goal_involvements_per_90: 0.33, expected_goals_conceded_per_90: 1.55, starts: 26, starts_per_90: 0.76, clean_sheets_per_90: 0.0, chance_of_playing_this_round: 50, chance_of_playing_next_round: 75, news: "Knock - 50% chance of playing this week", news_added: "2025-04-14T08:00:00Z", transfers_in: 120000, transfers_out: 180000, transfers_in_event: 4000, transfers_out_event: 28000, value_form: "0.52", value_season: "18.1", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: 1, in_dreamteam: false, dreamteam_count: 1, squad_number: null },
    { id: 304, code: 304, web_name: "Gross", first_name: "Pascal", second_name: "Gross", photo: "304.jpg", team: 4, team_code: 8, element_type: 3, status: "a", now_cost: 58, cost_change_event: 0, cost_change_start: 1, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "11.8", total_points: 128, event_points: 6, points_per_game: "3.8", form: "5.2", ep_this: "5.0", ep_next: "5.2", minutes: 2880, goals_scored: 6, assists: 8, clean_sheets: 0, goals_conceded: 0, yellow_cards: 2, red_cards: 0, saves: 0, bonus: 22, bps: 580, influence: "440.4", creativity: "520.6", threat: "380.4", ict_index: "134.4", ict_index_rank: 28, ict_index_rank_type: 2, expected_goals: "4.8", expected_assists: "6.8", expected_goal_involvements: "11.6", expected_goals_conceded: "42.1", expected_goals_per_90: 0.15, expected_assists_per_90: 0.21, expected_goal_involvements_per_90: 0.36, expected_goals_conceded_per_90: 1.31, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.0, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 180000, transfers_out: 90000, transfers_in_event: 18000, transfers_out_event: 8000, value_form: "0.90", value_season: "22.1", penalties_order: null, direct_freekicks_order: 1, corners_and_indirect_freekicks_order: 2, in_dreamteam: false, dreamteam_count: 2, squad_number: null },

    // FWDs (3)
    { id: 400, code: 400, web_name: "Haaland", first_name: "Erling", second_name: "Haaland", photo: "400.jpg", team: 12, team_code: 43, element_type: 4, status: "a", now_cost: 147, cost_change_event: 0, cost_change_start: -3, cost_change_event_fall: 0, cost_change_start_fall: 3, selected_by_percent: "52.4", total_points: 196, event_points: 8, points_per_game: "5.8", form: "7.4", ep_this: "6.8", ep_next: "7.0", minutes: 2880, goals_scored: 22, assists: 4, clean_sheets: 7, goals_conceded: 38, yellow_cards: 2, red_cards: 0, saves: 0, bonus: 40, bps: 880, influence: "720.4", creativity: "140.2", threat: "1480.8", ict_index: "234.0", ict_index_rank: 5, ict_index_rank_type: 1, expected_goals: "24.8", expected_assists: "3.4", expected_goal_involvements: "28.2", expected_goals_conceded: "38.5", expected_goals_per_90: 0.77, expected_assists_per_90: 0.11, expected_goal_involvements_per_90: 0.88, expected_goals_conceded_per_90: 1.20, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.21, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 1400000, transfers_out: 280000, transfers_in_event: 160000, transfers_out_event: 28000, value_form: "0.50", value_season: "13.3", penalties_order: 1, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 10, squad_number: null },
    { id: 401, code: 401, web_name: "Isak", first_name: "Alexander", second_name: "Isak", photo: "401.jpg", team: 14, team_code: 4, element_type: 4, status: "a", now_cost: 90, cost_change_event: 1, cost_change_start: 5, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "28.4", total_points: 168, event_points: 9, points_per_game: "5.3", form: "7.8", ep_this: "7.2", ep_next: "7.0", minutes: 2700, goals_scored: 19, assists: 5, clean_sheets: 7, goals_conceded: 28, yellow_cards: 1, red_cards: 0, saves: 0, bonus: 38, bps: 820, influence: "640.4", creativity: "180.2", threat: "1240.8", ict_index: "206.0", ict_index_rank: 8, ict_index_rank_type: 1, expected_goals: "17.4", expected_assists: "4.2", expected_goal_involvements: "21.6", expected_goals_conceded: "28.1", expected_goals_per_90: 0.58, expected_assists_per_90: 0.14, expected_goal_involvements_per_90: 0.72, expected_goals_conceded_per_90: 0.94, starts: 30, starts_per_90: 0.88, clean_sheets_per_90: 0.23, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 720000, transfers_out: 180000, transfers_in_event: 88000, transfers_out_event: 12000, value_form: "0.87", value_season: "18.7", penalties_order: 1, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 7, squad_number: null },
    { id: 402, code: 402, web_name: "Weghorst", first_name: "Wout", second_name: "Weghorst", photo: "402.jpg", team: 8, team_code: 54, element_type: 4, status: "a", now_cost: 40, cost_change_event: 0, cost_change_start: -1, cost_change_event_fall: 0, cost_change_start_fall: 1, selected_by_percent: "3.8", total_points: 68, event_points: 2, points_per_game: "2.2", form: "2.0", ep_this: "2.2", ep_next: "2.4", minutes: 1980, goals_scored: 4, assists: 3, clean_sheets: 0, goals_conceded: 0, yellow_cards: 2, red_cards: 0, saves: 0, bonus: 8, bps: 320, influence: "280.4", creativity: "120.2", threat: "480.4", ict_index: "88.0", ict_index_rank: 78, ict_index_rank_type: 3, expected_goals: "4.2", expected_assists: "2.4", expected_goal_involvements: "6.6", expected_goals_conceded: "42.1", expected_goals_per_90: 0.19, expected_assists_per_90: 0.11, expected_goal_involvements_per_90: 0.30, expected_goals_conceded_per_90: 1.91, starts: 22, starts_per_90: 0.65, clean_sheets_per_90: 0.0, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 40000, transfers_out: 80000, transfers_in_event: 2000, transfers_out_event: 12000, value_form: "0.50", value_season: "17.0", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 0, squad_number: null },

    // Extra players for transfer recommendations (not in squad)
    { id: 500, code: 500, web_name: "Saka", first_name: "Bukayo", second_name: "Saka", photo: "500.jpg", team: 1, team_code: 3, element_type: 3, status: "a", now_cost: 98, cost_change_event: 1, cost_change_start: 5, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "38.2", total_points: 198, event_points: 10, points_per_game: "5.8", form: "8.8", ep_this: "8.4", ep_next: "8.0", minutes: 2880, goals_scored: 14, assists: 11, clean_sheets: 14, goals_conceded: 26, yellow_cards: 1, red_cards: 0, saves: 0, bonus: 44, bps: 920, influence: "720.4", creativity: "840.6", threat: "880.4", ict_index: "244.4", ict_index_rank: 3, ict_index_rank_type: 1, expected_goals: "12.4", expected_assists: "9.8", expected_goal_involvements: "22.2", expected_goals_conceded: "28.5", expected_goals_per_90: 0.39, expected_assists_per_90: 0.31, expected_goal_involvements_per_90: 0.69, expected_goals_conceded_per_90: 0.89, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.41, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 1800000, transfers_out: 200000, transfers_in_event: 260000, transfers_out_event: 10000, value_form: "0.90", value_season: "20.2", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: true, dreamteam_count: 16, squad_number: null },
    { id: 501, code: 501, web_name: "Toney", first_name: "Ivan", second_name: "Toney", photo: "501.jpg", team: 3, team_code: 36, element_type: 4, status: "a", now_cost: 72, cost_change_event: 1, cost_change_start: 3, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "14.2", total_points: 148, event_points: 8, points_per_game: "4.5", form: "6.8", ep_this: "6.4", ep_next: "6.2", minutes: 2790, goals_scored: 14, assists: 8, clean_sheets: 0, goals_conceded: 0, yellow_cards: 3, red_cards: 0, saves: 0, bonus: 28, bps: 720, influence: "580.4", creativity: "280.2", threat: "980.4", ict_index: "184.0", ict_index_rank: 12, ict_index_rank_type: 1, expected_goals: "12.8", expected_assists: "6.4", expected_goal_involvements: "19.2", expected_goals_conceded: "48.5", expected_goals_per_90: 0.41, expected_assists_per_90: 0.21, expected_goal_involvements_per_90: 0.62, expected_goals_conceded_per_90: 1.56, starts: 31, starts_per_90: 0.91, clean_sheets_per_90: 0.0, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 380000, transfers_out: 120000, transfers_in_event: 48000, transfers_out_event: 8000, value_form: "0.94", value_season: "20.6", penalties_order: 1, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 5, squad_number: null },
    { id: 502, code: 502, web_name: "Muniz", first_name: "Rodrigo", second_name: "Muniz", photo: "502.jpg", team: 8, team_code: 54, element_type: 4, status: "a", now_cost: 62, cost_change_event: 1, cost_change_start: 4, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "21.8", total_points: 152, event_points: 10, points_per_game: "4.7", form: "7.4", ep_this: "7.0", ep_next: "6.8", minutes: 2880, goals_scored: 16, assists: 6, clean_sheets: 0, goals_conceded: 0, yellow_cards: 2, red_cards: 0, saves: 0, bonus: 30, bps: 760, influence: "620.4", creativity: "180.2", threat: "1040.8", ict_index: "184.0", ict_index_rank: 11, ict_index_rank_type: 1, expected_goals: "13.8", expected_assists: "4.8", expected_goal_involvements: "18.6", expected_goals_conceded: "42.1", expected_goals_per_90: 0.43, expected_assists_per_90: 0.15, expected_goal_involvements_per_90: 0.58, expected_goals_conceded_per_90: 1.31, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.0, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 580000, transfers_out: 100000, transfers_in_event: 72000, transfers_out_event: 6000, value_form: "1.19", value_season: "24.5", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 6, squad_number: null },
    { id: 503, code: 503, web_name: "Castagne", first_name: "Timothy", second_name: "Castagne", photo: "503.jpg", team: 8, team_code: 54, element_type: 2, status: "a", now_cost: 52, cost_change_event: 1, cost_change_start: 3, cost_change_event_fall: 0, cost_change_start_fall: 0, selected_by_percent: "15.4", total_points: 132, event_points: 8, points_per_game: "4.1", form: "6.2", ep_this: "5.8", ep_next: "5.4", minutes: 2880, goals_scored: 2, assists: 7, clean_sheets: 9, goals_conceded: 32, yellow_cards: 3, red_cards: 0, saves: 0, bonus: 24, bps: 620, influence: "480.4", creativity: "380.6", threat: "220.4", ict_index: "108.0", ict_index_rank: 48, ict_index_rank_type: 2, expected_goals: "1.6", expected_assists: "5.8", expected_goal_involvements: "7.4", expected_goals_conceded: "34.5", expected_goals_per_90: 0.05, expected_assists_per_90: 0.18, expected_goal_involvements_per_90: 0.23, expected_goals_conceded_per_90: 1.07, starts: 34, starts_per_90: 1.0, clean_sheets_per_90: 0.26, chance_of_playing_this_round: null, chance_of_playing_next_round: null, news: "", news_added: null, transfers_in: 280000, transfers_out: 90000, transfers_in_event: 32000, transfers_out_event: 6000, value_form: "1.19", value_season: "25.4", penalties_order: null, direct_freekicks_order: null, corners_and_indirect_freekicks_order: null, in_dreamteam: false, dreamteam_count: 3, squad_number: null },
  ],
};

export const demoFixtures: Fixture[] = [
  { id: 1, code: 1, event: 35, team_h: 11, team_a: 7, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-19T14:00:00Z", minutes: 0, team_h_difficulty: 1, team_a_difficulty: 5, started: false, pulse_id: 1 },
  { id: 2, code: 2, event: 35, team_h: 1, team_a: 17, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-19T11:30:00Z", minutes: 0, team_h_difficulty: 2, team_a_difficulty: 4, started: false, pulse_id: 2 },
  { id: 3, code: 3, event: 35, team_h: 12, team_a: 20, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-19T14:00:00Z", minutes: 0, team_h_difficulty: 2, team_a_difficulty: 4, started: false, pulse_id: 3 },
  { id: 4, code: 4, event: 35, team_h: 5, team_a: 13, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-20T13:00:00Z", minutes: 0, team_h_difficulty: 2, team_a_difficulty: 3, started: false, pulse_id: 4 },
  { id: 5, code: 5, event: 35, team_h: 3, team_a: 9, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-20T15:00:00Z", minutes: 0, team_h_difficulty: 2, team_a_difficulty: 4, started: false, pulse_id: 5 },
  { id: 6, code: 6, event: 35, team_h: 4, team_a: 15, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-20T15:00:00Z", minutes: 0, team_h_difficulty: 3, team_a_difficulty: 4, started: false, pulse_id: 6 },
  { id: 7, code: 7, event: 35, team_h: 14, team_a: 6, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-20T15:00:00Z", minutes: 0, team_h_difficulty: 1, team_a_difficulty: 5, started: false, pulse_id: 7 },
  { id: 8, code: 8, event: 35, team_h: 8, team_a: 16, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-20T15:00:00Z", minutes: 0, team_h_difficulty: 1, team_a_difficulty: 5, started: false, pulse_id: 8 },
  // GW 36
  { id: 9, code: 9, event: 36, team_h: 7, team_a: 11, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-26T14:00:00Z", minutes: 0, team_h_difficulty: 5, team_a_difficulty: 1, started: false, pulse_id: 9 },
  { id: 10, code: 10, event: 36, team_h: 17, team_a: 4, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-26T14:00:00Z", minutes: 0, team_h_difficulty: 3, team_a_difficulty: 3, started: false, pulse_id: 10 },
  { id: 11, code: 11, event: 36, team_h: 20, team_a: 12, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-26T14:00:00Z", minutes: 0, team_h_difficulty: 4, team_a_difficulty: 2, started: false, pulse_id: 11 },
  { id: 12, code: 12, event: 36, team_h: 1, team_a: 5, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-04-27T13:00:00Z", minutes: 0, team_h_difficulty: 3, team_a_difficulty: 3, started: false, pulse_id: 12 },
  // GW 37
  { id: 13, code: 13, event: 37, team_h: 11, team_a: 12, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-05-03T14:00:00Z", minutes: 0, team_h_difficulty: 4, team_a_difficulty: 4, started: false, pulse_id: 13 },
  { id: 14, code: 14, event: 37, team_h: 1, team_a: 14, team_h_score: null, team_a_score: null, finished: false, finished_provisional: false, kickoff_time: "2025-05-03T14:00:00Z", minutes: 0, team_h_difficulty: 3, team_a_difficulty: 3, started: false, pulse_id: 14 },
];

// Demo picks — intentionally sub-optimal: Trippier (injured) in starting XI,
// Mykolenko (bench-warmer) as first bench player, Andreas (doubtful) starting.
export const demoPicksResponse: PicksResponse = {
  picks: [
    { element: 101, position: 1, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 56, purchase_price: 53 },
    { element: 200, position: 2, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 78, purchase_price: 75 },
    { element: 201, position: 3, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 56, purchase_price: 55 },
    { element: 202, position: 4, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 60, purchase_price: 58 },
    { element: 203, position: 5, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 68, purchase_price: 71 }, // injured, should bench
    { element: 300, position: 6, multiplier: 2, is_captain: true, is_vice_captain: false, selling_price: 132, purchase_price: 128 },
    { element: 301, position: 7, multiplier: 1, is_captain: false, is_vice_captain: true, selling_price: 108, purchase_price: 105 },
    { element: 302, position: 8, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 76, purchase_price: 74 },
    { element: 303, position: 9, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 54, purchase_price: 55 }, // doubtful, risky start
    { element: 400, position: 10, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 147, purchase_price: 150 },
    { element: 401, position: 11, multiplier: 1, is_captain: false, is_vice_captain: false, selling_price: 90, purchase_price: 88 },
    // bench
    { element: 204, position: 12, multiplier: 0, is_captain: false, is_vice_captain: false, selling_price: 44, purchase_price: 44 },
    { element: 304, position: 13, multiplier: 0, is_captain: false, is_vice_captain: false, selling_price: 58, purchase_price: 57 },
    { element: 402, position: 14, multiplier: 0, is_captain: false, is_vice_captain: false, selling_price: 40, purchase_price: 41 },
    { element: 100, position: 15, multiplier: 0, is_captain: false, is_vice_captain: false, selling_price: 45, purchase_price: 45 },
  ],
  chips: [],
  entry_history: {
    event: 35,
    points: 0,
    total_points: 1840,
    rank: 0,
    rank_sort: 0,
    overall_rank: 284000,
    bank: 8, // £0.8m in bank
    value: 1008, // squad value £100.8m
    event_transfers: 0,
    event_transfers_cost: 0,
    points_on_bench: 0,
  },
  automatic_subs: [],
};

export const demoEntry: EntryResponse = {
  id: DEMO_TEAM_ID,
  name: "Demo FPL Team",
  player_first_name: "Demo",
  player_last_name: "Manager",
  summary_overall_points: 1840,
  summary_overall_rank: 284000,
  summary_event_points: 0,
  summary_event_rank: 0,
  current_event: DEMO_GW,
  last_deadline_bank: 8,
  last_deadline_value: 1008,
  last_deadline_total_transfers: 24,
  kit: null,
  leagues: { classic: [], h2h: [], cup: null, cup_matches: null },
  favourite_team: null,
  joined_time: "2024-08-01T00:00:00Z",
  started_event: 1,
  extra_entry: null,
  years_active: 1,
};
